services:
  - type: web
    name: stock-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb://localhost:27017/gestionstock
      - key: JWT_SECRET
        value: secret123456